### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Legrems** [infeeeee/kimai2-cmd#34]
When i want to start a measurement:
```
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request.request [as _callback] (/snapshot/kimai2-cmd/kimai2-cmd.js:84:32)
    at Request.init.self.callback (/snapshot/kimai2-cmd/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/kimai2-cmd/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/kimai2-cmd/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
 ```

When using the cli with the linux executable. I'm on arch 6.7.5.

I want to point that all the settings are correct, and i'm able to list the projects from the remote

**Comment by infeeeee** [comment]
Hello I don't know and I haven't used kimai or this tool for years. My js knowledge faded as well. 

If anyone want to fix it or fork it I'm ok with that, I would accept PRs.
